apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumsumoh
  labels:
    app: dumsumoh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dumsumoh
  template:
    metadata:
      labels:
        app: dumsumoh
    spec:
      containers:
      - name: dumsumoh
        image: priyansh21/dumsumoh:tagname 
        ports:
        - containerPort: 8050
